`timescale 1 ps / 1 ps
// pll30: DE2-115 CLOCK_50 (50 MHz) -> 30 MHz solver clock.
// fp64_add is ~29 ns combinational (Cyclone IV has no hard FP); 30 MHz
// (33.33 ns period) closes timing without pipelining every fp64_add.
// ALTPLL: VCO = 50 * 12 = 600 MHz, c0 = 600/20 = 30 MHz.
module pll30 (
    input  wire areset,
    input  wire inclk0,
    output wire c0,
    output wire locked
);
    wire [4:0] clk_out;
    assign c0 = clk_out[0];

    altpll #(
        .bandwidth_type("AUTO"),
        .clk0_divide_by(20),
        .clk0_duty_cycle(50),
        .clk0_multiply_by(12),
        .clk0_phase_shift("0"),
        .compensate_clock("CLK0"),
        .inclk0_input_frequency(20000),
        .intended_device_family("Cyclone IV E"),
        .lpm_hint("CBX_MODULE_PREFIX=pll30"),
        .lpm_type("altpll"),
        .operation_mode("NORMAL"),
        .pll_type("AUTO"),
        .port_activeclock("PORT_UNUSED"),
        .port_areset("PORT_USED"),
        .port_clkbad0("PORT_UNUSED"),
        .port_clkbad1("PORT_UNUSED"),
        .port_clkloss("PORT_UNUSED"),
        .port_clkswitch("PORT_UNUSED"),
        .port_configupdate("PORT_UNUSED"),
        .port_fbin("PORT_UNUSED"),
        .port_inclk0("PORT_USED"),
        .port_inclk1("PORT_UNUSED"),
        .port_locked("PORT_USED"),
        .port_pfdena("PORT_UNUSED"),
        .port_phasecounterselect("PORT_UNUSED"),
        .port_phasedone("PORT_UNUSED"),
        .port_phasestep("PORT_UNUSED"),
        .port_phaseupdown("PORT_UNUSED"),
        .port_pllena("PORT_UNUSED"),
        .port_scanaclr("PORT_UNUSED"),
        .port_scanclk("PORT_UNUSED"),
        .port_scanclkena("PORT_UNUSED"),
        .port_scandata("PORT_UNUSED"),
        .port_scandataout("PORT_UNUSED"),
        .port_scandone("PORT_UNUSED"),
        .port_scanread("PORT_UNUSED"),
        .port_scanwrite("PORT_UNUSED"),
        .port_clk0("PORT_USED"),
        .port_clk1("PORT_UNUSED"),
        .port_clk2("PORT_UNUSED"),
        .port_clk3("PORT_UNUSED"),
        .port_clk4("PORT_UNUSED"),
        .port_clk5("PORT_UNUSED"),
        .port_clk6("PORT_UNUSED"),
        .port_clk7("PORT_UNUSED"),
        .port_clk8("PORT_UNUSED"),
        .port_clk9("PORT_UNUSED"),
        .port_ena("PORT_UNUSED"),
        .self_reset_on_loss_lock("OFF"),
        .using_fbmimicbidir_port("OFF"),
        .width_clock(5)
    ) altpll_component (
        .areset(areset),
        .inclk({1'b0, inclk0}),
        .clk(clk_out),
        .locked(locked),
        .activeclock(),
        .clkbad(),
        .clkloss(),
        .configupdate(),
        .extclk(),
        .fbin(),
        .fbout(),
        .pfdena(),
        .phasecounterselect(),
        .phasedone(),
        .phasestep(),
        .phaseupdown(),
        .pllena(),
        .scanaclr(),
        .scanclk(),
        .scanclkena(),
        .scandata(),
        .scandataout(),
        .scandone(),
        .scanread(),
        .scanwrite(),
        .sclkout0(),
        .sclkout1(),
        .clkena(),
        .extclken(),
        .vcooverrange(),
        .vcounderrange()
    );
endmodule
